
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build first job
    - bash: echo $(PipeLineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo build second job  
- stage: DevDeploy
  variables:
   Stage: Dev
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo $(Stage)
   
- stage: QADeploy
  variables:
   Stage: QA
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps:
    - bash: echo $(Stage)
- stage: PeridDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: PeridDeploy
    steps:
    - bash: echo PeridDeploy   
  
