trigger:
- master

# strategy:
#  matrix:
#   linux:
#    operatingSystem: 'ubuntu-latest'
#   mac:
#    operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build Stage
  jobs:
   - job: BuildJob
     steps:
     - bash: echo "Do the Build"
- stage: DevDeploy Stage
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy: 
     runOnce:
       deploy:
         steps:
           - script: echo "Deploy to Dev"  
- stage: QA Stage
  jobs:
  - deployment: QAJob
    environment: QA
    strategy: 
     runOnce:
       deploy:
         steps:
           - script: echo "Deploy to Dev"  






