trigger:
- master

strategy:
 matrix:
  linux:
   operatingSystem: 'ubuntu-latest'
  mac:
   operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo runing on the $(operatingSystem)
  displayName: 'Run a one-line script'


